- name: Installer Flutter
    uses: subosito/flutter-action@v2
    with:
      flutter-version: '3.47.2'
      channel: 'stable'

  - name: Générer la structure Android standard
    run: |
      flutter create --platforms=android --org com.nabilainas.pdfeditor temp_app
      cp -r lib/. temp_app/lib/
      cp pubspec.yaml temp_app/pubspec.yaml

  - name: Autoriser l'accès à internet
    run: |
      sed -i '/<manifest /a\    <uses-permission android:name="android.permission.INTERNET" />' temp_app/android/app/src/main/AndroidManifest.xml

  - name: Installer les dépendances
    working-directory: temp_app
    run: flutter pub get

  - name: Compiler l'APK
    working-directory: temp_app
    run: flutter build apk --release

  - name: Publier l'APK
    uses: actions/upload-artifact@v4
    with:
      name: application-pdf-apk
      path: temp_app/build/app/outputs/flutter-apk/app-release.apk
